import { describe, it, expect } from 'vitest'
import { mount } from '@vue/test-utils'
import { createPinia } from 'pinia'
import FormBuilder from '../../components/FormBuilder.vue'
import { useFormBuilderStore } from '@/stores/formBuilder'

function mountWithStore() {
  const pinia = createPinia()
  const wrapper = mount(FormBuilder, {
    global: { plugins: [pinia] },
    attachTo: document.body,
  })
  const store = useFormBuilderStore()
  return { wrapper, store }
}

describe('Configuration panel UX', () => {
  it('adds, edits and removes options for select field', async () => {
    const { wrapper, store } = mountWithStore()

    // Add a select field; store auto-selects it
    store.addField('select')
    await wrapper.vm.$nextTick()

    const getOptions = () => (store.selectedField?.options || [])
    const startLen = getOptions().length

    // Click Add option
    const addBtn = wrapper.find('button:contains("Add option")')
    // Fallback if :contains selector not supported: find by text
    const addByText = addBtn.exists() ? addBtn : wrapper.findAll('button').find(b => b.text().toLowerCase().includes('add option'))!
    expect(addByText.exists ? addByText.exists() : !!addByText).toBeTruthy()
    // @ts-ignore
    await (addByText.trigger ? addByText.trigger('click') : addByText.trigger('click'))
    await wrapper.vm.$nextTick()

    expect(getOptions().length).toBe(startLen + 1)

    // Edit first option label and expect slug value update when it was autogenerated
    const labelInputs = wrapper
      .findAll('input')
      .filter(n => (n.attributes('placeholder') || '').toLowerCase().includes('option label'))
    expect(labelInputs.length).toBeGreaterThan(0)
    await labelInputs[0].setValue('Premium Plan')
    await wrapper.vm.$nextTick()
    expect(getOptions()[0].label).toBe('Premium Plan')
    // Value should be slugified if it matched optionN prior
    expect(getOptions()[0].value).toBeTypeOf('string')

    // Remove last option
    const removeButtons = wrapper.findAll('button').filter(b => b.text().toLowerCase() === 'remove')
    expect(removeButtons.length).toBeGreaterThan(0)
    await removeButtons[removeButtons.length - 1].trigger('click')
    await wrapper.vm.$nextTick()
    expect(getOptions().length).toBe(startLen)

    wrapper.unmount()
  })
})
